### ISSUE TITLE
[tutorial] several bugs following the guide

### ISSUE THREAD

**Issue by diramazioni** [punkave/apostrophe#833]
I'm following the **very** well written tutorial, making my first steps in discovering how it works, and I see how much work has been put in the docs and in the framework to make the life of a dev easier. Even if I'm still in the early stage and I haven't finished to review it all I've already discovered several **bugs/issues** I group them here to eventually split them in separate issues:

_minor docs mistakes_:
- [ ] in [drawer-widget/index.js](http://apostrophecms.org/docs/tutorials/getting-started/custom-widgets.html#adding-a-java-script-widget-player-on-the-browser-side) `      self.pushAsset('script', 'always', { when: 'always' });` is missing
- [ ] in lib/modules/drawer-widgets/public/css/always.less both .drawer-title and .drawer rules are ignored leaving it visible. I had to specify a class in the widget.html like 

```
<h4><a data-drawer-title class="drawer-title" href="#">{{ data.widget.title }}</a></h4>
<div data-drawer class="drawer-body">
  {{ apos.area(data.widget, 'content', 
    { edit: false }) }}
</div>
```
and call `.drawer-title` and  `.drawer-body ` in the css

_Visualization bugs_
- [ ] When I click inside a `'apostrophe-rich-text'` it goes into edit mode correctly then I click _outside_ of it but **inside** of another rich-text. Now the rich text that **received** the click doesn't have the ability to enter in edit mode and I have to reload the page to be able to edit again. To be clear, the problem happens in the rich-text that got the outside-click not the one initially edited. If I click outside in an area not editable (like the background) this problem doesn't manifest. This bug also disable the bottom bar where there is the + sign to add new widgets, so this is the most problematic because disrupt the workflow completely.

- [ ] I have made a simple navigation exactly like the one described in the tutorial and inserted in a template (ie in a overridden outerLayout.html) when I make any edit action in the admin toolbar, like inserting a new Page or Person, as soon as I press save, my navigation get removed from the DOM (need a reload). 

- [ ] keep following the tutorial in lib/modules/people-widgets/views/widget.html the thumbnail is not displayed and a white bar appears instead:
![image](https://cloud.githubusercontent.com/assets/682046/23568439/c80db43c-005a-11e7-8a6b-4b2a32d310b7.png)

- [ ] following the drawer example when I insert content in the modal window the available widgets get partially hidden this is a minor thing because if you scroll they appears but still it's not desirable. 
![image](https://cloud.githubusercontent.com/assets/682046/23566242/5f944fd2-0051-11e7-90aa-913ac643be74.png)

- [ ] The UI for moving the elements **and** the secondary button like `Edit People` that appears on hover covers other elements and make impossible to correctly edit the elements underneath. One floating ui with absolute position is already problematic two are just too much! Any chance to make it more design friendly all in one toolbar with a toggle button to set display none? Consider that what is hard to do with a mouse it may be impossible to do in a mobile device

Let me know if I have to clarify any of these issue. thanks for looking into this!

**Comment by boutell** [comment]
Hi Eli, thanks for the kind words and the feedback!

Going through these...

1. Pushing the script asset always.js: this is automatic, because `apostrophe-widgets` pushes it, we're subclassing `apostrophe-widgets`, and a pushed script or CSS asset is automatically pushed (if it exists) from the public/js or public/css folder for every subclass as well. It's a convenience that eliminates the need to add code every time — you just create the file and it gets sent. Works nicely with the way your CSS overrides and JavaScript subclasses what came before.

2. Those CSS bugs: guilty as charged, fixing these in the docs, thanks!

3. Issue with clicking on editors consecutively: I see what you mean. I just pushed a fix for this which will get published today. Thanks!

4. Overriding outerLayout is usually not what you want. You should put your navigation in a `layout.html` which your page templates extend, and your `layout.html` should extend `data.outerLayout`, overriding the `beforeMain`, `main` and `afterMain` blocks.

The refresh of the main content area that takes place when pieces are edited via the admin bar is performed to ensure that if you changed something that is in a widget somewhere, that change is now visible. `outerLayout` is outside of that region.

I am not 500% sure this is all of what's going on in your case, but please try it, and if things still seem broken, please share a github repository where I can see the issue.

5. The white bar issue: please share a github repository where I can see this issue in action.

6. Floating UI interfering with other things: cc @stuartromanek for some advice here. I'm not sure what the best approach is. Again, maybe helpful to share a repo where we can have a look at it. I know these issues get worked out in our client projects and it may be that we need to share a more complete set of example styles for having this be a pleasant experience.

(Editing on mobile is not considered in scope for Apostrophe at the moment.)

**Comment by diramazioni** [comment]
Thanks for looking into this!
1. ah my bad, this was me trying out things, I've actually broke the pattern renaming  always.js into something else so I had to explicitly push it specifying a name 
2. great
3. TERRIFIC!
4. OK this fix it! 
5. I will if I have to but really it's just following what it's written in the tutorial (that btw should really have it's own git repo or be based on the demo sandbox). The image in the thumbnail field just doesn't show up.
6. I've tracked down the css issue it's the `overflow-y: scroll; ` in `/modules/apostrophe-modal/css/components/modal-tabs.less` removing this rule it removes the initial height computation so content can be added and scroll happens normally
7. ok this is the _most_ problematic issue that it's driving me **crazy**  
![crazy_admin](https://cloud.githubusercontent.com/assets/682046/23581449/54fc57fe-0114-11e7-98e0-1e4ae7a73988.gif)
now seriously, mobile or not, **I can't use apostrophe** until this is fixed! The elements are literally unselectable when are not made of several lines. This makes impossible to deal with any widget that are 1 line height as output. Try to replicate the drawer example or the page-link and both will have just a line and you can't easily select them and move around!
Part of the problem is that the elements are there with the opacity on 0 but they react on hover. It should have display: none and be shown when necessary
One possible solution could be to make the apos-area-widget-controls be wrapped inside the element so it enlarge on hover and a space it's created around the data element pushing the other lines below.
Or better not be triggered on hover and bind it to a key press (e) or tiny icon appear on hover and when you hover/click that the other UI appears. 
What you think?

**Comment by boutell** [comment]
Switching between basic rich text widgets etc. works reasonably well in the stock sandbox:

http://g.recordit.co/J9ztzYjyst.gif

However I'm plodding through our own tutorial, cleaning things up and looking out for the things you reported. So I'll let you know when I get to my page link widget and see if I have a similar problem.

**Comment by diramazioni** [comment]
Also in your gif you can see that the UI for the Rich Text covers the one for moving the element around.
The problem for me was menu reordering pageLinks in the modal dialog. Getting the right hover combination with this margins it's not possible.
I've no time now to look into this but I was planing to resolve this issue sending a user.js with inside an hover listener for the one-line output that would "push" the other elements creating the space for the control buttons.
One thing that would greatly mitigate the issue is having a closing icon to the side of the appearing UI. The underling interaction with, for example, the drawer title to make appear the content on click, get disrupted if the UI gets on it's way and you don't have way to close it. 
Another way, as already mentioned, would be to leave certain controls normally close and enable them with a click on smaller icons, I this is the best solution from a usability perspective
Anyway it's great to see you follow up on this!

**Comment by stuartromanek** [comment]
Just catching up to this issue ... we've consolidated editing controls to one bar per widget, overlapping can still happen on tightly stacked widgets but its at least intuitive to target the control you want.

Glad we were able to improve on the tutorial, @diramazioni I encourage you to make more granular issues if there are still problems.

Closing this.
